from typing import Optional, List
from sqlmodel import SQLModel, Field, Relationship
from passlib import hash
from datetime import datetime  

# Database models for the application
class User(SQLModel, table=True):
    id : int = Field(primary_key=True, index=True)
    email : str = Field(index=True)
    hashed_password : str = Field(index=True)
    role : int = Field(index=True, foreign_key="role.id", default=3) # Default role is 3 (user)
    employee : Optional["Employee"] = Relationship(back_populates="user")
    overtimerequests : List["OvertimeRequest"] = Relationship(back_populates="owner") 
    travelcostrequests : List["TravelcostRequest"] = Relationship(back_populates="owner")
    examparticipations : List["ExamParticipation"] = Relationship(back_populates="owner") 

    def verify_password(self, password: str):
        return hash.bcrypt.verify(password, self.hashed_password)

class Compensation(SQLModel, table=True):
    id : Optional[int] = Field(default=None, primary_key=True)
    type : str = Field(index=True)
    compensation : float = Field(index=True)

class Role(SQLModel, table=True):
    id : Optional[int] = Field(default=None, primary_key=True)
    name : str = Field(index=True)

class School(SQLModel, table=True):
    id : Optional[int] = Field(default=None, primary_key=True)
    kodikos: int = Field(index=True) 
    name : str = Field(index=True)
    email : str = Field(index=True)
    employees: List["Employee"] = Relationship(back_populates="school")
    latitude : Optional[float] = Field(default=None)
    longitude : Optional[float] = Field(default=None)

class Employee(SQLModel, table=True):
    id : Optional[int] = Field(default=None, primary_key=True)
    afm : Optional [int] = Field(index=True, default=None)
    am : Optional [int] = Field(index=True, default=None)
    category : Optional[str] = Field(default=None)
    contract : Optional[str] = Field(default=None)
    mk : Optional[int] = Field(default=None)
    first_name : str = Field(index=True)
    last_name :str = Field(index=True)   
    email : str = Field(index=True)
    iban : Optional[str] = Field(default=None)
    school_id : Optional[int] = Field(default=None, foreign_key="school.id", ondelete="SET NULL")
    user_id : Optional[int] = Field(default=None, foreign_key="user.id")
    school: Optional[School] = Relationship(back_populates="employees")
    user : Optional[User] = Relationship(back_populates="employee")

class RegisterRequest(SQLModel, table=True):
    id : Optional[int] = Field(default=None, primary_key=True, index=True)
    category : str = Field(index=True)
    afm : Optional [int] = Field(index=True, default=None)
    kodikos : Optional [int] = Field(index=True, default=None)
    email : str = Field(index=True)
    hashed_password : str = Field(index=True)
    submitted: int = Field(default=0)
    stimestamp : Optional[datetime] = Field(default=None)
    check_result : Optional[str] = Field(default=None)
    approved : int = Field(default=0)
    atimestamp : Optional[datetime] = Field(default=None)

class OvertimePayment(SQLModel, table=True):
    id : Optional[int] = Field(default=None, primary_key=True, index=True)
    name : str = Field(index=True)
    month : str = Field(index=True) 
    year : int = Field(index=True)
    submitted : int = Field(default=0)
    stimestamp : Optional[datetime] = Field(default=None)
    overtimeinventories : List ["OvertimeInventory"] = Relationship(back_populates="overtimepayment") 
    overtimerequests : List ["OvertimeRequest"] = Relationship(back_populates="overtimepayment") 

class OvertimeInventory(SQLModel, table=True):
    id : Optional[int] = Field(default=None, primary_key=True, index=True)
    payment_id : Optional[int] = Field(default=None, foreign_key="overtimepayment.id", ondelete="SET NULL")
    school : str = Field(index=True)
    month : str = Field(index=True) 
    year : int = Field(index=True)
    submitted : int = Field(default=0)
    stimestamp : Optional[datetime] = Field(default=None)
    approved : int = Field(default=0)
    atimestamp : Optional[datetime] = Field(default=None)
    inserted : int = Field(default=0)
    itimestamp : Optional[datetime] = Field(default=None)
    overtimerequests : List ["OvertimeRequest"] = Relationship(back_populates="overtimeinventory") 
    overtimepayment : Optional[OvertimePayment] = Relationship(back_populates="overtimeinventories")

class OvertimeRequest(SQLModel, table=True):
    id : Optional[int] = Field(default=None, primary_key=True, index=True)
    owner_id : int = Field(foreign_key="user.id")
    inventory_id : Optional[int] = Field(default=None, foreign_key="overtimeinventory.id", ondelete="SET NULL")
    payment_id : Optional[int] = Field(default=None, foreign_key="overtimepayment.id", ondelete="SET NULL")
    first_name : str = Field(index=True)
    last_name : str = Field(index=True)
    afm : int = Field(index=True)
    school : str = Field(index=True)
    month : str = Field(index=True)
    year : int = Field(index=True)
    number_of_overtimes : int = Field(index=True)
    compensation: int = Field(default=0)
    mtpy: float = Field(default=0)
    eisfora: float = Field(default=0)
    foros : float = Field(default=0)
    payable : float = Field(default=0)
    assignment: Optional[str] = Field(default=None) 
    final : int = Field(default=0)
    ftimestamp : Optional[datetime] = Field(default=None)
    schedule : Optional[str] = Field(default=None)
    approved : int = Field(default=0)
    atimestamp : Optional[datetime] = Field(default=None)
    inserted : int = Field(default=0)
    itimestamp : Optional[datetime] = Field(default=None)
    submitted : int = Field(default=0)
    stimestamp : Optional[datetime] = Field(default=None)
    paid : int = Field(default=0)
    ptimestamp : Optional[datetime] = Field(default=None)
    owner : Optional [User] = Relationship(back_populates="overtimerequests")
    overtimeinventory : Optional[OvertimeInventory] = Relationship(back_populates="overtimerequests")
    overtimepayment : Optional[OvertimePayment] = Relationship(back_populates="overtimerequests")

class TravelcostPayment(SQLModel, table=True):
    id : Optional[int] = Field(default=None, primary_key=True, index=True)
    name : str = Field(index=True)
    month : str = Field(index=True) 
    year : int = Field(index=True)
    submitted : int = Field(default=0)
    stimestamp : Optional[datetime] = Field(default=None)
    travelcostinventories : List ["TravelcostInventory"] = Relationship(back_populates="travelcostpayment") 
    travelcostrequests : List ["TravelcostRequest"] = Relationship(back_populates="travelcostpayment") 

class TravelcostInventory(SQLModel, table=True):
    id : Optional[int] = Field(default=None, primary_key=True, index=True)
    payment_id : Optional[int] = Field(default=None, foreign_key="travelcostpayment.id", ondelete="SET NULL")
    school : str = Field(index=True)
    month : str = Field(index=True) 
    year : int = Field(index=True)
    submitted : int = Field(default=0)
    stimestamp : Optional[datetime] = Field(default=None)
    approved : int = Field(default=0)
    atimestamp : Optional[datetime] = Field(default=None)
    inserted : int = Field(default=0)
    itimestamp : Optional[datetime] = Field(default=None)
    travelcostrequests : List ["TravelcostRequest"] = Relationship(back_populates="travelcostinventory") 
    travelcostpayment : Optional[TravelcostPayment] = Relationship(back_populates="travelcostinventories")
 
class TravelcostRequest(SQLModel, table=True):
    id : Optional[int] = Field(default=None, primary_key=True, index=True)
    owner_id : int = Field(foreign_key="user.id")
    inventory_id : Optional[int] = Field(default=None, foreign_key="travelcostinventory.id", ondelete="SET NULL")
    payment_id : Optional[int] = Field(default=None, foreign_key="travelcostpayment.id", ondelete="SET NULL")
    first_name : str = Field(index=True)
    last_name : str = Field(index=True)
    afm : int = Field(index=True)
    start_school : str = Field(index=True)
    destination_school : str = Field(index=True)
    month : str = Field(index=True)
    year : int = Field(index=True)
    number_of_travels : int = Field(index=True)
    distance: int = Field(default=0)
    compensation: int = Field(default=0)
    distribution: Optional[str] = Field(default=None) 
    license: Optional[str] = Field(default=None) 
    final : int = Field(default=0)
    ftimestamp : Optional[datetime] = Field(default=None)
    schedule : Optional[str] = Field(default=None)
    approved : int = Field(default=0)
    atimestamp : Optional[datetime] = Field(default=None)
    inserted : int = Field(default=0)
    itimestamp : Optional[datetime] = Field(default=None)
    submitted : int = Field(default=0)
    stimestamp : Optional[datetime] = Field(default=None)
    paid : int = Field(default=0)
    ptimestamp : Optional[datetime] = Field(default=None)
    owner : Optional [User] = Relationship(back_populates="travelcostrequests")
    travelcostinventory : Optional[TravelcostInventory] = Relationship(back_populates="travelcostrequests")
    travelcostpayment : Optional[TravelcostPayment] = Relationship(back_populates="travelcostrequests")

class ExamPayment(SQLModel, table=True):
    id : Optional[int] = Field(default=None, primary_key=True, index=True)
    name : str = Field(index=True)
    type : str = Field(index=True)
    month : str = Field(index=True) 
    year : int = Field(index=True)
    submitted : int = Field(default=0)
    stimestamp : Optional[datetime] = Field(default=None)
    examinventories : List ["ExamInventory"] = Relationship(back_populates="exampayment") 
    examparticipations : List ["ExamParticipation"] = Relationship(back_populates="exampayment") 

class ExamInventory(SQLModel, table=True):
    id : Optional[int] = Field(default=None, primary_key=True, index=True)
    payment_id : Optional[int] = Field(default=None, foreign_key="exampayment.id", ondelete="SET NULL")
    name : str = Field(index=True)
    type : str = Field(index=True)
    school : str = Field(index=True)
    month : str = Field(index=True) 
    year : int = Field(index=True)
    decree: Optional[str] = Field(default=None) 
    affirmation: Optional[str] = Field(default=None) 
    submitted : int = Field(default=0)
    stimestamp : Optional[datetime] = Field(default=None)
    approved : int = Field(default=0)
    atimestamp : Optional[datetime] = Field(default=None)
    inserted : int = Field(default=0)
    itimestamp : Optional[datetime] = Field(default=None)
    paid : int = Field(default=0)
    ptimestamp : Optional[datetime] = Field(default=None)
    examparticipations : List ["ExamParticipation"] = Relationship(back_populates="examinventory") 
    exampayment : Optional[ExamPayment] = Relationship(back_populates="examinventories")

class ExamParticipation(SQLModel, table=True):
    id : Optional[int] = Field(default=None, primary_key=True, index=True)
    owner_id : int = Field(foreign_key="user.id")
    inventory_id : Optional[int] = Field(default=None, foreign_key="examinventory.id", ondelete="SET NULL")
    payment_id : Optional[int] = Field(default=None, foreign_key="exampayment.id", ondelete="SET NULL")
    type : str = Field(index=True)
    role : str = Field(index=True)
    last_name : str = Field(index=True)
    first_name : str = Field(index=True)
    afm : int = Field(index=True)   
    am : int = Field(index=True) 
    category : str = Field(index=True)
    contract : str = Field(index=True)
    mk : int = Field(index=True) 
    iban : str = Field(index=True)
    month : str = Field(index=True)
    year : int = Field(index=True)
    number_of_exams : int = Field(index=True)
    compensation: int = Field(default=0)
    mtpy: float = Field(default=0)
    eisfora: float = Field(default=0)
    foros : float = Field(default=0)
    payable : float = Field(default=0)
    inserted : int = Field(default=0)
    itimestamp : Optional[datetime] = Field(default=None)
    paid : int = Field(default=0)
    ptimestamp : Optional[datetime] = Field(default=None)
    owner : Optional [User] = Relationship(back_populates="examparticipations")
    examinventory : Optional[ExamInventory] = Relationship(back_populates="examparticipations")
    exampayment : Optional[ExamPayment] = Relationship(back_populates="examparticipations")
